### ISSUE TITLE
Doesn't detect anything on macOS Monterey

### ISSUE THREAD

**Issue by 1ngki** [wmorland/alfred-py3-default-browser#25]
`[05:25:25.174] Py3 Default Browser[Script Filter] Queuing argument '(null)'
[05:25:25.252] Py3 Default Browser[Script Filter] Script with argv '(null)' finished
[05:25:25.264] ERROR: Py3 Default Browser[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A131F7C1-120F-4080-A739-E357320942A8/defaultbrowser.py", line 15, in <module>
    import objc
  File "/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A131F7C1-120F-4080-A739-E357320942A8/lib/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: cannot import name '_objc' from partially initialized module 'objc' (most likely due to a circular import) (/Users/username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A131F7C1-120F-4080-A739-E357320942A8/lib/objc/__init__.py)`

**Comment by wmorland** [comment]
This should be fixed in 1.1.0 by https://github.com/wmorland/alfred-py3-default-browser/pull/26
